///\file
/// Contains defines and constants depending on the configuration choosen during the CMake build process.
/// This file is generated by CMake.

#ifndef PAL_CONFIG_H
#define PAL_CONFIG_H

#include <pal/ConfigVersion.h>

/// Name of the default physics engine, that is to say the higest priority availaible engine.
const char * const DEFAULT_ENGINE = "BULLET";



#endif	// PAL_CONFIG_H
